# Generated by Django 4.2.6 on 2023-10-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1500)),
                ('answer', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('previous_question', models.CharField(max_length=1500)),
            ],
        ),
    ]
