# Generated by Django 4.2.6 on 2023-10-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_quiz_previous_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_update',
            field=models.DateField(auto_now=True),
        ),
    ]
