# Generated by Django 4.2.6 on 2023-10-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quiz_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
