# Generated by Django 4.2.6 on 2023-10-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_quiz_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='previous_question',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
